<?php

use dev\suvera\exms\data\entity\Subject;

$subject = $subject ?? new Subject();
?>
<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Subject - <?php $subject->id ?? 'Create'; ?></h4>
            <div class="alert alert-danger" role="alert" id="error_div" style="display: none;">
            </div>
            <form class="forms-sample" method="POST">
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Subject name" value="<?php echo $subject->name ?? ''; ?>" maxlength="255">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-1">
                        <button type="button" class="btn btn-primary" onclick="submitForm();" id="submitBtn">Submit</button>
                    </div>
                    <div class="col-sm-1">
                        <a href="/exms/admin/ui/subject" class="btn btn-light">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    function submitForm() {
        var btn = document.getElementById('submitBtn');
        btn.disabled = true;

        var name = document.getElementById('name').value;
        var error_div = document.getElementById('error_div');
        error_div.style.display = 'none';
        var err = [];
        if (name == '') {
            err.push('Name is required');
        }
        if (err != '') {
            error_div.innerHTML = '<ul class="mb-0"><li>' + err.join("</li><li>") + '</li></ul>';
            error_div.style.display = 'block';
            btn.disabled = false;
            return;
        }
        var data = {
            name: name
        };
        var url = '/exms/admin/subject<?php echo isset($subject->id) ? '/' . $subject->id : ''; ?>';
        $.ajax({
            type: "<?php echo isset($subject->id) ? 'PATCH' : 'POST'; ?>",
            url: url,
            data: JSON.stringify(data),
            success: function(response) {
                if (response.status == 200) {
                    window.location.href = '/exms/admin/ui/subject';
                } else {
                    error_div.innerHTML = 'Error: ' + response.error + '';
                    error_div.style.display = 'block';
                }
            },
            dataType: 'json',
            contentType: 'application/json'
        }).fail(function(jqXHR) {
            error_div.innerHTML = 'Error while updating subject';
            if (jqXHR.responseJSON && jqXHR.responseJSON.error) {
                error_div.innerHTML = 'Error: ' + jqXHR.responseJSON.error + '';
            }
            error_div.style.display = 'block';

        }).always(function() {
            btn.disabled = false;
        });
    }
</script>