<?php

$subjects = $subjects ?? [];
$pageSize = $pageSize ?? 20;
$pageNum = $pageNum ?? 0;
$baseUrl = $_SERVER['REQUEST_URI'];
if (!str_contains($baseUrl, '?')) {
    $baseUrl .= '?';
}
?>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Exam Papers</h4>
            <div class="form-group row">
                <div class="col-sm-9">
                    <form method="GET" id="list_search_from">
                        <div class="input-group">
                            <div class="input-group-prepend">
                                <span class="input-group-text" id="search">
                                    <i class="mdi mdi-magnify"></i>
                                </span>
                            </div>
                            <input type="text" class="form-control" id="list_search" name="search" placeholder="Search by Name" value="<?php echo isset($search) ? htmlentities($search) : ''; ?>" maxlength="255">
                        </div>
                    </form>
                </div>
                <div class="col-sm-3">
                    <a href="/exms/admin/ui/subject/create" class="btn btn-info"><i class="mdi mdi-plus btn-icon-prepend"></i>Create</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Created On</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        $subjectCount = 0;
                        foreach ($subjects as $subject):
                            $subjectCount++;
                        ?>
                            <tr>
                                <td>
                                    <?php echo $subject->id; ?>
                                </td>
                                <td>
                                    <?php echo $subject->name; ?>
                                </td>
                                <td>
                                    <?php echo $subject->createdAt->format('Y-m-d H:i:s'); ?>
                                </td>
                                <td>
                                    <div class="dropdown">
                                        <button class="btn btn-link btn-rounded btn-fw" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                                            <i class="mdi mdi-dots-vertical"></i>
                                        </button>
                                        <ul class="dropdown-menu">
                                            <li><a class="dropdown-item" href="/exms/admin/ui/subject/edit/<?php echo $subject->id; ?>">
                                                    <i class="mdi mdi-pencil text-info"></i> Edit
                                                </a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        <?php
                        endforeach;
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="pt-1">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end">
                        <?php
                        $pageUrl = preg_replace('/&page=\d+/', '', $baseUrl);
                        if ($pageNum <= 0) {
                            echo '<li class="page-item disabled"><span class="page-link">Previous</span></li>';
                        } else {
                            echo '<li class="page-item"><a class="page-link" href="' . $pageUrl . '&page=' . ($pageNum - 1) . '">Previous</a></li>';
                        }
                        ?>
                        <li class="page-item disabled"><span class="page-link text-dark">Page <?php echo $pageNum + 1; ?>
                                showing <?php echo $subjectCount; ?> records
                            </span></li>
                        <?php
                        if ($subjectCount < $pageSize) {
                            echo '<li class="page-item disabled"><span class="page-link">Next</span></li>';
                        } else {
                            echo '<li class="page-item"><a class="page-link" href="' . $pageUrl . '&page=' . ($pageNum + 1) . '">Next</a></li>';
                        }
                        ?>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>