<div class="col-md-12 grid-margin">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title display3 text-danger"><?php echo $pageTitle; ?></h4>
            <p class="card-description text-danger">
                <?php echo isset($message) ? $message : ''; ?>
            </p>
            <div class="row">
                <?php echo isset($description) ? $description : ''; ?>
            </div>
        </div>
    </div>
</div>