 </div>
 <!-- content-wrapper ends -->
 <footer class="footer">
     <div class="d-sm-flex justify-content-center">
         <span class="text-muted text-center text-sm-left d-block d-sm-inline-block">Copyright © <a href="https://suvera.xyz/" target="_blank" style="font-size: 115%;">suvera </a><?php echo date('Y') ?></span>
     </div>
 </footer>
 <!-- partial -->
 </div>
 <!-- main-panel ends -->
 </div>
 <!-- page-body-wrapper ends -->
 </div>

 <script src="/exms/admin/vendors/base/vendor.bundle.base.js"></script>
 <script src="/exms/admin/js/off-canvas.js"></script>
 <script src="/exms/admin/js/hoverable-collapse.js"></script>
 <script src="/exms/admin/js/template.js"></script>
 <script src="/exms/admin/js/main.js"></script>
 <script src="/exms/admin/js/file-upload.js"></script>
 <script src="/exms/admin/js/Chart.min.js"></script>
 <script src="/exms/admin/js/hoverable-collapse.js"></script>
 <script src="/exms/admin/js/jquery.cookie.js"></script>
 <script src="/exms/admin/js/jquery.dataTables.js"></script>
 <script src="/exms/admin/js/off-canvas.js"></script>
 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/css/selectize.default.min.css" integrity="sha512-pTaEn+6gF1IeWv3W1+7X7eM60TFu/agjgoHmYhAfLEU8Phuf6JKiiE8YmsNC0aCgQv4192s4Vai8YZ6VNM6vyQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
 <script src=" https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.15.2/js/selectize.min.js" integrity="sha512-IOebNkvA/HZjMM7MxL0NYeLYEalloZ8ckak+NDtOViP7oiYzG5vn6WVXyrJDiJPhl4yRdmNAG49iuLmhkUdVsQ==" crossorigin="anonymous" referrerpolicy="no-referrer">
 </script>

 <script>
     $(function() {
         $("select").selectize({
             plugins: ["clear_button", "autofill_disable", "auto_position"],
         });
     });
 </script>

 </body>

 </html>