<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="<?php echo isset($pageDescription) ? $pageDescription : 'Admin'; ?>">
    <meta name="author" content="suvera">
    <meta name="generator" content="suvera">
    <title><?php echo isset($pageTitle) ? $pageTitle : ''; ?></title>
    <link rel="stylesheet" href="/exms/admin/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="/exms/admin/vendors/base/vendor.bundle.base.css">
    <link rel="stylesheet" href="/exms/admin/css/style.css">
    <link rel="shortcut icon" type="image/jpeg" href="/exms/images/logo_small.jpg" />
    <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
    <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js"></script>
    <style>
    </style>
</head>

<body>
    <div class="container-scroller">
        <?php include __DIR__ . '/_topnav.phtml'; ?>
        <div class="container-fluid page-body-wrapper">
            <?php include __DIR__ . '/_sidebar.phtml'; ?>
            <div class="main-panel">
                <div class="content-wrapper">