<h1><?php echo htmlspecialchars($paperName, ENT_QUOTES, 'UTF-8');
    if (isset($totalQuestions)) {
        echo ' (' . htmlspecialchars($totalQuestions, ENT_QUOTES, 'UTF-8') . ')';
    }
    ?></h1>

<h5>Please add questions:</h5>
<div>
    <a href="/exms/paper/view?paperId=<?php echo htmlspecialchars($paperId, ENT_QUOTES, 'UTF-8'); ?>" target="_blank">View Questions</a> |
    <a href="/exms/paper/view?withAnswers=1&paperId=<?php echo htmlspecialchars($paperId, ENT_QUOTES, 'UTF-8'); ?>" target="_blank">View Questions with Answers</a>
</div>
<form action="/exms/paper/add_questions?paperId=<?php echo htmlspecialchars($paperId, ENT_QUOTES, 'UTF-8'); ?>" method="POST">
    <?php if (isset($error) && $error) : ?>
        <div class="error-message"><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></div>
    <?php endif; ?>
    <div>
        <label for="questions">Questions:</label>
        <textarea name="questions" id="questions" rows="10" placeholder="Enter questions here"></textarea>
    </div>
    <div>
        <button type="submit" class="btn-blue">Submit</button>
    </div>
</form>