<!DOCTYPE html>
<html lang="en">

<head>
    <title><?php echo isset($pageTitle) ? $pageTitle : ''; ?></title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            margin: 40px;
            background-color: #f8f8f8;
            /* Light gray */
            color: #333;
            /* Dark gray text */
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            border-radius: 8px;
        }

        h1 {
            text-align: center;
            color: #7e5716;
            /* Bootstrap blue */
            margin-bottom: 20px;
        }

        p {
            text-indent: 2em;
            margin-bottom: 15px;
        }

        .div-error {
            color: red;
            margin-bottom: 10px;
        }

        .btn-blue {
            background-color: #007bff;
            color: white;
            padding: 10px 20px;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }

        input[type="text"] {
            padding: 10px;
            margin-bottom: 10px;
            border: 1px solid #ccc;
            border-radius: 4px;
            font-size: 16px;
            width: 98%;
        }

        input[type="text"]:focus {
            outline: none;
            border-color: #007bff;
            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
        }

        textarea {
            width: 98%;
            padding: 10px;
            border: 1px solid #ccc;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
            border-radius: 4px;
            font-size: 16px;
            resize: vertical;
            margin-bottom: 10px;
        }

        textarea:focus,
        textarea:hover {
            outline: none;
            border-color: #007bff;
            box-shadow: 0 0 5px rgba(0, 123, 255, 0.5);
        }


        .error-message {
            background-color: #f8d7da;
            color: #721c24;
            border: 1px solid #f5c6cb;
            padding: 10px;
            border-radius: 4px;
            display: flex;
            margin-bottom: 10px;
        }

        .error-message::before {
            content: "⚠️";
            margin-right: 5px;
        }

        a {
            color: #007BFF;
            text-decoration: none;
            transition: color 0.3s ease, text-decoration 0.3s ease;
        }

        a:hover {
            color: #0056b3;
            text-decoration: underline;
        }

        a:active {
            color: #004085;
            text-decoration: underline;
        }

        a:visited {
            color: #007BFF;
        }

        a:focus {
            outline: 2px dashed #0056b3;
            outline-offset: 2px;
        }
    </style>
</head>

<body>
    <div class="container">