<h1>New Paper</h1>

<h5>Please enter question paper name:</h5>
<form action="/exms/paper/new" method="POST">
    <?php if (isset($error) && $error) : ?>
        <div class="error-message"><?php echo htmlspecialchars($error, ENT_QUOTES, 'UTF-8'); ?></div>
    <?php endif; ?>
    <div>
        <input type="text" id="paperName" name="paperName" placeholder="Enter paper name" maxlength="255" />
    </div>
    <div>
        <button type="submit" class="btn-blue">Submit</button>
    </div>
</form>