<!DOCTYPE html>
<html>

<head>
    <title><?php echo isset($pageTitle) ? $pageTitle : ''; ?></title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background-color: #bbbbbb;
            margin: 0;
            padding: 0;
        }

        h2 {
            text-align: center;
            color: #333;
            border-bottom: 1px solid #ccc;
            /* Light gray line */
            padding-bottom: 10px;
        }

        .question-container {
            background-color: white;
            padding: 10px;
            margin: 10px auto;
            width: 90%;
            max-width: 900px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
            border-radius: 10px;
            position: relative;
            /* For positioning the answer */
        }

        .question-container:nth-child(even) {
            background-color: #f9f9f9;
        }

        .question-title {
            margin-bottom: 8px;
            display: block;
            font-size: 17px;
            font-weight: bold;
            unicode-bidi: isolate;
        }

        .topic {
            font-size: 12px;
            font-weight: normal;
            margin-bottom: 8px;
        }

        .option {
            font-size: 15px;
            background-color: #e5e5e5;
            padding: 10px;
            margin-bottom: 8px;
            border-radius: 5px;
            cursor: pointer;
            transition: background-color 0.3s;
        }

        .option:hover {
            background-color: #d0d0d0;
        }

        .answer {
            font-family: 'Courier New', Courier, monospace;
            font-size: 15px;
            background-color: #003300;
            color: #f9f9f9;
            padding: 15px;
            margin-top: 10px;
            border-radius: 5px;
        }

        .explanation {
            margin-left: 20px;
            line-break: strict;
        }

        .exam-info {
            text-align: center;
            margin-bottom: 5px;
            color: #555;
            font-size: 11px;
        }
    </style>
</head>

<body>

    <h2><?php echo htmlspecialchars($paperName, ENT_QUOTES, 'UTF-8');
        if (isset($totalQuestions)) {
            echo ' (' . htmlspecialchars($totalQuestions, ENT_QUOTES, 'UTF-8') . ')';
        }
        ?></h2>

    <div class="exam-info">
        Questions: <?php echo count($questions); ?> <span style="padding-left: 10px;padding-right:10px">|</span> Exam Time: <?php echo $timeMins; ?> minutes
    </div>

    <?php
    $optionCodes = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'];
    foreach ($questions as $idx => $question) :

        $options = $question['options'];
        $optionsHasAbcd = false;
        $answerCode = '';
        $question['answer'] = trim($question['answer']);
        if (str_starts_with($options[0], '(a) ') && str_starts_with($options[1], '(b) ')) {
            $answerCode = $question['answer'];
            $optionsHasAbcd = true;
        }

    ?>
        <div class="question-container">
            <div class="question-title"><?php echo $idx + 1; ?>) <?php echo htmlspecialchars($question['question'], ENT_QUOTES, 'UTF-8'); ?></div>
            <div class="topic">Topic: <?php echo htmlspecialchars($question['course_topic'], ENT_QUOTES, 'UTF-8'); ?></div>
            <?php
            foreach ($options as $optIndx => $option) :
                if (!$optionsHasAbcd && $option == $question['answer']) {
                    $answerCode = $optionCodes[$optIndx] . ')';
                }
            ?>
                <div class="option"><?php echo $optionsHasAbcd ? '' : $optionCodes[$optIndx] . ')'; ?> <?php echo htmlspecialchars($option, ENT_QUOTES, 'UTF-8'); ?></div>
            <?php endforeach; ?>
            <?php if (isset($withAnswers) && $withAnswers) : ?>
                <div class="answer">
                    Answer: <?php echo $answerCode; ?> <?php echo $optionsHasAbcd ? '' : htmlspecialchars($question['answer'], ENT_QUOTES, 'UTF-8'); ?><br>
                    <u>Explanation:</u> <br>
                    <div class="explanation">
                        <?php
                        $explanation = htmlspecialchars($question['explanation'], ENT_QUOTES, 'UTF-8');
                        echo $explanation;
                        ?></div>
                </div>
            <?php endif; ?>
        </div>
    <?php endforeach; ?>

</body>

</html>