<div class="row">
    <div class="col-md-4 col-lg-5">
        <?php if ($error) : ?>
            <div class="alert alert-danger" role="alert"> <?php echo $error; ?></div>
        <?php endif; ?>
        <div class=" col-md-6">
            <h2>Admin Login</h2>
        </div>
        <form class="">
            <div class="mb-3">
                <label for="username" class="form-label required">Username</label>
                <input type="text" class="form-control" id="username" name="username" required>
            </div>

            <div class="mb-3">
                <label for="password" class="form-label required">Password</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>

            <button type="submit" class="btn btn-primary">Sign in</button>

        </form>
    </div>
</div>