<?php

use dev\suvera\exms\utils\UiUtils;
use dev\suvera\exms\data\entity\ExamPaper;

$paper = $paper ?? new ExamPaper();
?><div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Paper: <?php echo $paper->name; ?></h4>
            <div class="alert alert-danger" role="alert" id="error_div" style="display: none;">
            </div>
            <form class="forms-sample" method="POST">
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="<?php echo htmlentities($paper->name); ?>" maxlength="255">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Status</label>
                    <div class="col-sm-9">
                        <select name="status" id="status" class="">
                            <?php echo UiUtils::selectOptions2($paper->status->getKeyValues(), $paper->status->value); ?>
                        </select>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="subject_id" class="col-sm-2 col-form-label">Subject</label>
                    <div class="col-sm-9">
                        <select name="subject_id" id="subject_id" class="">
                            <?php echo UiUtils::selectOptions($subjects, $paper->subjectId); ?>
                        </select>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="classes" class="col-sm-2 col-form-label">Classes</label>
                    <div class="col-sm-9">
                        <div class="row">
                            <?php
                            $classes = $classes ?? [];
                            foreach ($classes as $classId => $className) {
                                $checked = '';
                                foreach ($paper->classes as $class) {
                                    if ($class->classId == $classId) {
                                        $checked = 'checked';
                                    }
                                }
                                echo '<div class="col-sm-2"><div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" class="form-check-input" name="classes" value="' . $classId . '" ' . $checked . '>
                                        ' . $className . '
                                        <i class="input-helper"></i></label>
                                </div></div>';
                            }
                            ?>
                        </div>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="topics" class="col-sm-2 col-form-label">Exam Time (mins)</label>
                    <div class="col-sm-9">
                        <input type="number" class="form-control" id="exam_time" name="exam_time" value="<?php echo $paper->totalTimeMins; ?>" min="1" max="100">
                        <span class="card-description">Total Questions: <?php echo $paper->totalQuestions; ?></span>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-1">
                        <button type="button" class="btn btn-primary" onclick="submitForm();" id="submitBtn">Submit</button>
                    </div>
                    <div class="col-sm-1">
                        <a href="/exms/admin/ui/exam_paper" class="btn btn-light">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
<script>
    function submitForm() {
        var btn = document.getElementById('submitBtn');
        btn.disabled = true;

        var name = document.getElementById('name').value;
        var status = document.getElementById('status').value;
        var subject_id = $('#subject_id').val();
        var classes = $('input:checkbox[name="classes"]:checked').map(function() {
            return $(this).val();
        }).get();
        var exam_time = document.getElementById('exam_time').value;
        var error_div = document.getElementById('error_div');
        error_div.style.display = 'none';
        var err = [];
        if (name == '') {
            err.push('Name is required');
        }
        if (status == '') {
            err.push('Status is required');
        }
        if (exam_time == '' || isNaN(exam_time)) {
            err.push('Exam time is required');
        }
        if (subject_id == '') {
            err.push('Subject is required');
        }
        if (classes == null || classes.length == 0) {
            err.push('Classes are required');
        }
        if (err != '') {
            error_div.innerHTML = '<ul class="mb-0"><li>' + err.join("</li><li>") + '</li></ul>';
            error_div.style.display = 'block';
            btn.disabled = false;
            return;
        }
        var data = {
            name: name,
            exam_time: exam_time,
            subject_id: subject_id,
            classes: classes,
            status: status
        };
        var url = '/exms/admin/exam_paper/<?php echo $paper->id; ?>';
        $.ajax({
            type: "PATCH",
            url: url,
            data: JSON.stringify(data),
            success: function(response) {
                if (response.status == 200) {
                    window.location.href = '/exms/admin/ui/exam_paper/<?php echo $paper->id; ?>';
                } else {
                    error_div.innerHTML = 'Error: ' + response.error + '';
                    error_div.style.display = 'block';
                }
            },
            dataType: 'json',
            contentType: 'application/json'
        }).fail(function(jqXHR) {
            error_div.innerHTML = 'Error while generating paper';
            if (jqXHR.responseJSON && jqXHR.responseJSON.error) {
                error_div.innerHTML = 'Error: ' + jqXHR.responseJSON.error + '';
            }
            error_div.style.display = 'block';

        }).always(function() {
            btn.disabled = false;
        });
    }
</script>