<div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Generate Paper with AI</h4>
            <form class="forms-sample" method="POST">
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="" maxlength="255">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Total Questions</label>
                    <div class="col-sm-9">
                        <input type="number" class="form-control" id="total" name="total" placeholder="Subject name" value="" min="1" max="100">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="subject_id" class="col-sm-2 col-form-label">Subject</label>
                    <div class="col-sm-9">
                        <select name="subject_id" id="subject_id" class="">
                            <option value="1">Mustard</option>
                            <option value="2">Ketchup</option>
                            <option value="3">Barbecue</option>
                        </select>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="classes" class="col-sm-2 col-form-label">Classes</label>
                    <div class="col-sm-9">
                        <select name="classes[]" id="classes" class="" multiple>
                            <option value="1">Mustard</option>
                            <option value="2">Ketchup</option>
                            <option value="3">Barbecue</option>
                        </select>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="topics" class="col-sm-2 col-form-label">Topics</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="topics" name="topics" placeholder="Comma seperated list of values" value="" maxlength="1024">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="api_token" class="col-sm-2 col-form-label">API Token*</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="api_token" name="api_token" placeholder="api token" value="" maxlength="512">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-1">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <div class="col-sm-1">
                        <button class="btn btn-light">Cancel</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>