<?php

use dev\suvera\exms\data\ClassData;
use dev\suvera\exms\data\ExamPaperStatus;

$papers = $papers ?? [];
?>
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Exam Papers</h4>
            <div class="form-group row">
                <div class="col-sm-9">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="search">
                                <i class="mdi mdi-magnify"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control" id="list_search" name="list_search" placeholder="Search by Name or Subject name" value="" maxlength="255">
                    </div>
                </div>
                <div class="col-sm-3">
                    <a href="/exms/admin/ui/exam_paper/generate" class="btn btn-info"><i class="mdi mdi-plus btn-icon-prepend"></i>Generate AI</a>
                    <a href="button" class="btn btn-secondary"><i class="mdi mdi-plus btn-icon-prepend"></i>Create</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Subject</th>
                            <th>Classes</th>
                            <th>Total Questions</th>
                            <th>Created On</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php
                        foreach ($papers as $paper):
                        ?>
                            <tr>
                                <td>
                                    <a href="/exms/admin/ui/exam_paper/<?php echo $paper->id; ?>"><?php echo $paper->name; ?></a>
                                </td>
                                <td>
                                    <span class=" badge rounded-pill <?php echo $paper->status != ExamPaperStatus::PREPARING ? 'text-bg-success' : 'text-bg-warning'; ?>"><?php echo $paper->status->value; ?></span>
                                </td>
                                <td>
                                    <?php echo $paper->subject->name; ?>
                                </td>
                                <td>
                                    <?php
                                    $c = 0;
                                    foreach ($paper->classes as $class) {
                                        $c++;
                                        if ($c > 1) {
                                            echo ', ';
                                        }
                                        echo ClassData::getClassName($class->classId);
                                    }
                                    ?>
                                </td>
                                <td>
                                    <?php echo $paper->totalQuestions; ?>
                                </td>
                                <td>
                                    <?php echo $paper->createdAt->format('Y-m-d H:i:s'); ?>
                                </td>
                            </tr>
                        <?php
                        endforeach;
                        ?>
                    </tbody>
                </table>
            </div>
            <div class="pt-1">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end">
                        <li class="page-item disabled">
                            <span class="page-link">Previous</span>
                        </li>
                        <li class="page-item disabled"><span class="page-link text-dark">Page 1 showing 20 records</span></li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>