<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Exam Papers</h4>
            <div class="form-group row">
                <div class="col-sm-9">
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="search">
                                <i class="mdi mdi-magnify"></i>
                            </span>
                        </div>
                        <input type="text" class="form-control" id="list_search" name="list_search" placeholder="Search by Name or Subject name" value="" maxlength="255">
                    </div>
                </div>
                <div class="col-sm-3">
                    <a href="/exms/admin/ui/exam_paper/generate" class="btn btn-info"><i class="mdi mdi-plus btn-icon-prepend"></i>Generate AI</a>
                    <a href="button" class="btn btn-secondary"><i class="mdi mdi-plus btn-icon-prepend"></i>Create</a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Status</th>
                            <th>Subject</th>
                            <th>Classes</th>
                            <th>Total Questions</th>
                            <th>Created On</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="py-1">
                                <img src="../../images/faces/face2.jpg" alt="image" />
                            </td>
                            <td>
                                Messsy Adam
                            </td>
                            <td>
                                <div class="progress">
                                    <div class="progress-bar bg-danger" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </td>
                            <td>
                                $245.30
                            </td>
                            <td>
                                July 1, 2015
                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td class="py-1">
                                <img src="../../images/faces/face3.jpg" alt="image" />
                            </td>
                            <td>
                                John Richards
                            </td>
                            <td>
                                <div class="progress">
                                    <div class="progress-bar bg-warning" role="progressbar" style="width: 90%" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </td>
                            <td>
                                $138.00
                            </td>
                            <td>
                                Apr 12, 2015
                            </td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="pt-1">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-end">
                        <li class="page-item disabled">
                            <span class="page-link">Previous</span>
                        </li>
                        <li class="page-item disabled"><span class="page-link text-dark">Page 1 showing 20 records</span></li>
                        <li class="page-item">
                            <a class="page-link" href="#">Next</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</div>