<?php

use dev\suvera\exms\data\entity\Student;

$student = $student ?? new Student();
?><div class="col-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Student: <?php echo isset($student->name) ? $student->name : 'Create'; ?></h4>
            <div class="alert alert-danger" role="alert" id="error_div" style="display: none;">
            </div>
            <form class="forms-sample" method="POST">
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Name*</label>
                    <div class="col-sm-9">
                        <input type="text" class="form-control" id="name" name="name" placeholder="Name" value="<?php echo htmlentities($student->name ?? ''); ?>" maxlength="255">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Username*</label>
                    <div class="col-sm-9">
                        <?php echo htmlentities($student->username ?? ''); ?>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="name" class="col-sm-2 col-form-label">Email*</label>
                    <div class="col-sm-9">
                        <input type="email" class="form-control" id="email" name="email" placeholder="Email address" value="<?php echo htmlentities($student->email ?? ''); ?>" maxlength="255">
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <label for="classes" class="col-sm-2 col-form-label">Classes*</label>
                    <div class="col-sm-9">
                        <div class="row">
                            <?php
                            $classes = $classes ?? [];
                            foreach ($classes as $classId => $className) {
                                $checked = '';
                                foreach ($student->classes as $class) {
                                    if ($class->classId == $classId) {
                                        $checked = 'checked';
                                    }
                                }
                                echo '<div class="col-sm-2"><div class="form-check">
                                    <label class="form-check-label">
                                        <input type="checkbox" class="form-check-input" name="classes" value="' . $classId . '" ' . $checked . '>
                                        ' . $className . '
                                        <i class="input-helper"></i></label>
                                </div></div>';
                            }
                            ?>
                        </div>
                    </div>
                    <div class="col-sm-1"></div>
                </div>
                <div class="form-group row">
                    <div class="col-sm-1">
                        <button type="button" class="btn btn-primary" onclick="submitForm();" id="submitBtn">Submit</button>
                    </div>
                    <div class="col-sm-1">
                        <a href="/exms/admin/ui/student" class="btn btn-light">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="successModal" tabindex="-1" role="dialog" aria-labelledby="successModalTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="successModalTitle">Student created successfully</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="hideCredsModal();">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <pre id="creds_code">
Username: a
Password: b
                </pre>
                <div style="display:none;" class="text-success" id="copy_success_msg">Copied to clipboard</div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="hideCredsModal();">Close</button>
                <button type="button" class="btn btn-primary" onclick="performCopyCreds()">Copy to Clipboard</button>
            </div>
        </div>
    </div>
</div>
<script>
    function submitForm() {
        var btn = document.getElementById('submitBtn');
        var copyText = document.getElementById("creds_code");
        btn.disabled = true;

        var name = document.getElementById('name').value;
        var classes = $('input:checkbox[name="classes"]:checked').map(function() {
            return $(this).val();
        }).get();
        var email = document.getElementById('email').value;
        var error_div = document.getElementById('error_div');
        error_div.style.display = 'none';
        var err = [];
        if (name == '') {
            err.push('Name is required');
        }
        if (email == '') {
            err.push('Email is required');
        }
        if (classes == null || classes.length == 0) {
            err.push('Classes are required');
        }
        if (err != '') {
            error_div.innerHTML = '<ul class="mb-0"><li>' + err.join("</li><li>") + '</li></ul>';
            error_div.style.display = 'block';
            btn.disabled = false;
            return;
        }
        var data = {
            name: name,
            email: email,
            classes: classes
        };
        var url = '/exms/admin/student/<?php echo $student->id; ?>';
        $.ajax({
            type: "PATCH",
            url: url,
            data: JSON.stringify(data),
            success: function(response) {
                if (response.status == 200) {
                    window.location.href = '/exms/admin/ui/student/<?php echo $student->id; ?>';
                } else {
                    error_div.innerHTML = 'Error: ' + response.error + '';
                    error_div.style.display = 'block';
                }
            },
            dataType: 'json',
            contentType: 'application/json'
        }).fail(function(jqXHR) {
            error_div.innerHTML = 'Error while generating student';
            if (jqXHR.responseJSON && jqXHR.responseJSON.error) {
                error_div.innerHTML = 'Error: ' + jqXHR.responseJSON.error + '';
            }
            error_div.style.display = 'block';

        }).always(function() {
            btn.disabled = false;
        });
    }
</script>